# Generated by Django 3.2.14 on 2022-08-02 04:22

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('base', '0002_auto_20220802_0347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tags',
            new_name='tag',
        ),
    ]
