# Generated by Django 3.2.14 on 2022-08-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('N', 'Rather not to say'), ('M', 'Male'), ('F', 'Female')], default='N', max_length=1),
        ),
    ]
